name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle (Directly)
        # Is command mein hum ne wrapper ko bypass kar diya hai
        run: |
          sudo apt-get install -y gradle
          # Agar AttendBot folder ke andar hai to wahan jaye
          if [ -d "AttendBot" ]; then cd AttendBot; fi
          gradle assembleDebug --stacktrace

      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AttendBot-APK
          path: "**/app-debug.apk"
